筑巢信息/Zhuchao/LiveAzure/Tools/MyWorkplace_tiangang/Controllers/PrivateCategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using LiveAzure.Models;
using LiveAzure.Models.Member;
using LiveAzure.Resource.Stage;
using LiveAzure.Stage.Controllers;
using LiveAzure.Models.General;
using MVC.Controls;
using MVC.Controls.Grid;

namespace MyWorkplace_tiangang.Controllers
{
    public class PrivateCategoryController : BaseController
    {

        string LogName = "admin";

        public Guid GetOrganization()
        {
            MemberUser oUser = dbEntity.MemberUsers.Where(m => m.LoginName == LogName).Single();
            //MemberOrganization oOrganization = dbEntity.MemberOrganizations.Where(m => m.Gid == oUser.OrgID).Single();
            return (oUser.Gid);
        }
        //
        // GET: /Program/
        static byte nPrivateCategoryType = (byte)ModelEnum.PrivateCategoryType.PRODUCT;

        public ActionResult Index()
        {
            MemberUser oUser = dbEntity.MemberUsers.Where(m => m.LoginName == LogName).Single();
            MemberOrganization oOrganization = dbEntity.MemberOrganizations.Where(m => m.Gid == oUser.OrgID).Single();
            ViewBag.privateCategoryList = getPrivateCategoryTypeSelectlist();
            return View();
        }

        /// <summary>
        /// 返回生成树的json数据
        /// </summary>
        /// <returns></returns>
        public string TreeLoad()
        {
            var privateCategoryList = dbEntity.GeneralPrivateCategorys.Where(o => o.Parent == null && o.Deleted == false && o.Ctype == nPrivateCategoryType).ToList();

            int nPrivateCategoryCount = privateCategoryList.Count();

            List<LiveTreeNode> list = new List<LiveTreeNode>();

            foreach (var item in privateCategoryList)
            {
                LiveTreeNode treeNode = new LiveTreeNode();
                treeNode.id = item.Gid.ToString();
                treeNode.name = item.Name.GetResource(CurrentSession.Culture);
                treeNode.icon = "";
                treeNode.iconClose = "";
                treeNode.iconOpen = "";
                treeNode.nodeChecked = false;
                treeNode.nodeChecked = true;
                treeNode.progUrl = "";
                treeNode.nodes = new List<LiveTreeNode>();

                list.Add(treeNode);
            }

            string strTreeJson = CreateTree(list);

            return strTreeJson;

        }

        /// <summary>
        /// 异步展开树节点，返回展开节点的json字符串
        /// </summary>
        /// <param name="id">展开树节点的guid</param>
        /// <returns></returns>
        public string TreeExpand(Guid id)
        {
            string strTreeJson = "";

            //当展开root节点的时候
            if (id.ToString().Equals("00000000-0000-0000-0000-000000000000"))
            {
                var privateCategoryList = dbEntity.GeneralPrivateCategorys.Where(o => o.Parent == null && o.Deleted == false).ToList();

                int iProgCount = privateCategoryList.Count();

                List<LiveTreeNode> list = new List<LiveTreeNode>();

                foreach (var item in privateCategoryList)
                {
                    if (item.Deleted == false)
                    {
                        LiveTreeNode treeNode = new LiveTreeNode();
                        treeNode.id = item.Gid.ToString();
                        treeNode.name = item.Name.GetResource(CurrentSession.Culture);
                        treeNode.icon = "";
                        treeNode.iconClose = "";
                        treeNode.iconOpen = "";
                        treeNode.nodeChecked = false;
                        treeNode.isParent = false;
                        treeNode.progUrl = "";
                        treeNode.nodes = new List<LiveTreeNode>();

                        list.Add(treeNode);
                    }
                }

                strTreeJson = CreateTreeJson(list, "");
            }
            else                                                          //非root节点展开的时候，回传的gid不为空
            {
                GeneralPrivateCategory privateCategoryChildList = dbEntity.GeneralPrivateCategorys.Include("ChildItems").Where(p => p.Gid == id).Single();

                List<LiveTreeNode> list = new List<LiveTreeNode>();

                foreach (var item in privateCategoryChildList.ChildItems)
                {
                    if (item.Deleted == false)
                    {
                        LiveTreeNode treeNode = new LiveTreeNode();
                        treeNode.id = item.Gid.ToString();
                        treeNode.name = item.Name.GetResource(CurrentSession.Culture);
                        treeNode.icon = "../demo/zTreeStyle/img/edit.png";
                        treeNode.iconClose = "../demo/zTreeStyle/img/edit.png";
                        treeNode.iconOpen = "../demo/zTreeStyle/img/edit.png";
                        treeNode.nodeChecked = false;
                        treeNode.isParent = false;
                        treeNode.progUrl = "";
                        treeNode.nodes = new List<LiveTreeNode>();

                        list.Add(treeNode);
                    }
                }

                strTreeJson = CreateTreeJson(list, "");
            }

            return "[" + strTreeJson + "]";

        }

        /// <summary>
        /// 删除树节点
        /// </summary>
        /// <param name="id">选中树节点的guid</param>
        public void TreeRemove(Guid id)
        {
            Guid gid = id;

            GeneralPrivateCategory privateCategoryChildList = dbEntity.GeneralPrivateCategorys.Include("ChildItems").Where(p => p.Gid == id).Single();

            privateCategoryChildList.Deleted = true;

            DeleteChild(privateCategoryChildList.ChildItems.ToList<GeneralPrivateCategory>());

            dbEntity.SaveChanges();

        }

        /// <summary>
        /// 递归删除program的子项
        /// </summary>
        /// <param name="list">program子项的集合</param>
        public void DeleteChild(List<GeneralPrivateCategory> list)
        {
            int nListCount = list.Count;

            for (int i = 0; i < nListCount; i++)
            {
                if (list.ElementAt(i).ChildItems.Count > 0)
                {
                    list.ElementAt(i).Deleted = true;
                    DeleteChild(list.ElementAt(i).ChildItems.ToList<GeneralPrivateCategory>());
                }
                else
                {
                    list.ElementAt(i).Deleted = true;
                }
            }

        }

        /// <summary>
        /// 编辑程序
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult ProgramNodeEdit(Guid id)
        {
            var privateCategoryNode = dbEntity.GeneralStandardCategorys.Include("Parent").Where(s => s.Gid == id).Single();
            return PartialView("ProgramNodeEdit", privateCategoryNode);
        }

        /// <summary>
        /// 保存编辑程序
        /// </summary>
        /// <param name="gid"></param>
        /// <param name="privateCategoryNodeCollection"></param>
        /// <returns></returns>
        public ActionResult SavePrivateCategoryNode(Guid gid, FormCollection privateCategoryNodeCollection)
        {
            var selectProgram = dbEntity.GeneralStandardCategorys.Where(s => s.Gid == gid).Single();
            selectProgram.Code = privateCategoryNodeCollection["Code"];
            selectProgram.Name.Matter = privateCategoryNodeCollection["Name.Matter"];
            selectProgram.Sorting = Int32.Parse(privateCategoryNodeCollection["Sorting"]);

            dbEntity.SaveChanges();

            return RedirectToAction("Index");
        }

        /// <summary>
        /// 添加程序
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult ProgramNodeAdd(Guid id)
        {
            GeneralPrivateCategory oGeneralPrivateCategory = new GeneralPrivateCategory();

            oGeneralPrivateCategory.aParent = id;

            oGeneralPrivateCategory.Parent = dbEntity.GeneralPrivateCategorys.Where(p => p.Gid == id).Single();

            return View(oGeneralPrivateCategory);
        }

        /// <summary>
        /// 添加程序
        /// </summary>
        /// <param name="parentId"></param>
        /// <param name="programNodeCollection"></param>
        /// <returns></returns>
        public ActionResult AddProgramNode(Guid parentId, FormCollection programNodeCollection)
        {
            GeneralPrivateCategory oGeneralPrivateCategory = new GeneralPrivateCategory();
            oGeneralPrivateCategory.OrgID = GetOrganization();
            oGeneralPrivateCategory.aParent = parentId;
            oGeneralPrivateCategory.Code = programNodeCollection["Code"];
            oGeneralPrivateCategory.Sorting = Convert.ToInt32(programNodeCollection["Sorting"]);

            GeneralResource oResouce = new GeneralResource();
            oResouce.Code = "4534645";
            oResouce.Culture = 2052;
            oResouce.Matter = programNodeCollection["Name.Matter"];
            dbEntity.GeneralResources.Add(oResouce);

            oGeneralPrivateCategory.Name = oResouce;

            dbEntity.GeneralPrivateCategorys.Add(oGeneralPrivateCategory);

            dbEntity.SaveChanges();

            return RedirectToAction("Index");
        }

        public List<SelectListItem> getPrivateCategoryTypeSelectlist()
        {
            var oPrivateCategoryTypeName = Enum.GetNames(typeof(ModelEnum.PrivateCategoryType));
            var oPrivateCategoryTypevalues = (ModelEnum.PrivateCategoryType[])Enum.GetValues(typeof(ModelEnum.StandardCategoryType));

筑巢信息/Zhuchao/LiveAzure/Tools/MyWorkplace_tiangang/Controllers/StandardCategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MyWorkplace_tiangang.Controllers;
using LiveAzure.Models;
using LiveAzure.Utility;
using LiveAzure.Models.General;

namespace MyWorkplace_tiangang.Controllers
{
    public class StandardCategoryController : Controller
    {
        public LiveEntities dbEntity = new LiveEntities(ConfigHelper.LiveConnection.Connection);

        public ActionResult Index()
        {
            var oStandardCategories = dbEntity.GeneralStandardCategorys.Where(g => g.Parent == null && g.Deleted == false).ToList();

            ViewBag.standardCategoryList = getStandardCategoryTypeSelectlist();

            return View(oStandardCategories);
        }

        public ActionResult ChangeTree()
        {

            return PartialView();
        }

        public List<SelectListItem> getStandardCategoryTypeSelectlist()
        {
            var oStandardCategoryTypeName = Enum.GetNames(typeof(LiveAzure.Models.ModelEnum.StandardCategoryType));
            var oStandardCategoryTypevalues = (LiveAzure.Models.ModelEnum.StandardCategoryType[])Enum.GetValues(typeof(LiveAzure.Models.ModelEnum.StandardCategoryType));
            List<SelectListItem> oStandardCategoryTypeList = new List<SelectListItem>();
            int nStandardCategoryTypeCount = oStandardCategoryTypeName.Count();
            for (int i = 0; i < nStandardCategoryTypeCount; i++)
            {
                SelectListItem item = new SelectListItem
                {
                    Text = oStandardCategoryTypeName[i],
                    Value = ((byte)(oStandardCategoryTypevalues[i])).ToString()
                };
                oStandardCategoryTypeList.Add(item);
            }
            return oStandardCategoryTypeList;
        }
    }
}

筑巢信息/Zhuchao/LiveAzure/Tools/MyWorkplace_tiangang/Views/PrivateCategory/GetCType.cshtml
<script type="text/javascript">
    var nTreeObject = new treeObject();
    nTreeObject.createTree("tree", "/PrivateCategory/TreeLoad", "/PrivateCategory/TreeExpand", "", "rMenu", true);
</script>

筑巢信息/Zhuchao/LiveAzure/Tools/MyWorkplace_tiangang/Views/PrivateCategory/Index.cshtml
@using LiveAzure.Models.General
@model GeneralPrivateCategory

<script type="text/javascript" src="@Url.Content("~/Scripts/jquery-1.6.2.js")"></script>
<script type="text/javascript" src="@Url.Content("~/Scripts/LiveTree/jquery.ztree-2.6.js")"></script>
<script type="text/javascript" src="@Url.Content("~/Scripts/LiveTree/treeObject.js")"></script>

<script type="text/javascript">
  <!--
    var nTreeObject = new treeObject();
    nTreeObject.createTree("tree", "/PrivateCategory/TreeLoad", "/PrivateCategory/TreeExpand", "", "rMenu", true);
    function add_Node() {

        nTreeObject.add_TreeNode("rMenu");

        $.ajax({
            type: "POST",
            url: "/PrivateCategory/ProgramNodeAdd",
            data: { id: nTreeObject.selectNode.id },
            success: function (data) {
                $("#progAdd").html(data);
            }
        });
    }

    function edit_Node() {
        nTreeObject.edit_TreeNode("rMenu");

        $.ajax({
            type: "POST",
            url: "/PrivateCategory/ProgramNodeEdit",
            data: { id: nTreeObject.selectNode.id },
            success: function (data) {
                $("#progEdit").html(data);
            }
        });
    }

    function del_Node() {
        nTreeObject.del_TreeNode("tree", "/PrivateCategory/TreeRemove", "/PrivateCategory/TreeLoad", "rMenu");
    }

    function ShowTree(cType) {
        $.ajax({
            type: "POST",
            url: "/PrivateCategory/GetCType",
            data: { privateCategoryType: cType },
            success: function (data) {
                $("#tree").html(data);
            }
        })
    }
      //-->
</script>

<div class="display-field" id="drowdowndiv" >
    @LiveAzure.Resource.Model.General.GeneralPrivateCategory.Ctype
    @Html.DropDownListFor(model => model.Ctype, (List<SelectListItem>)ViewBag.privateCategoryList, new { OnChange = "ShowTree(this.value)" })
    @Html.ValidationMessageFor(model => model.Ctype)
</div>

<div id="otree">
    @*@{Html.RenderAction("GetCType", "StandardCategory");}*@
</div>

<table style="width:100%">
    <tr>
        <td style="width:50%">
            <div id="progMain">
            <ul id="tree" class="tree" style="width: 230px; overflow: auto;">
            </ul>
            <div id="rMenu" style="position: absolute; visibility: hidden;">
                <ul>
                <li>
                    <ul id="m_add" onclick="add_Node();">
                        <li>增加节点</li></ul>
                    <ul id="m_edit" onclick="edit_Node();">
                        <li>编辑节点</li></ul>
                    <ul id="m_delete" onclick="del_Node();">
                        <li>删除节点</li></ul>
                </li>
                </ul>
            </div>  
            </div>
        </td>
        <td style="width:50%">
            <div id="progAdd">
            </div>
            <div id="progEdit">
            </div>
        </td>
    </tr>
</table>

筑巢信息/Zhuchao/LiveAzure/Tools/MyWorkplace_tiangang/Views/PrivateCategory/ProgramNodeAdd.cshtml
@using LiveAzure.Models.General
@using LiveAzure.Resource.Stage;
@using LiveAzure.Resource.Model;
@model GeneralPrivateCategory
           
<script type="text/javascript" src="@Url.Content("~/Scripts/jquery-1.6.2.js")" ></script>
<script src="../../Scripts/jquery-1.5.1-vsdoc.js" type="text/javascript"></script>
<script type="text/javascript">

    function submitForm() {
        $("#programForm").submit();
    }
</script>

<div style="margin:2px;">
    <h2>@ProgramController.addProgramNode</h2>
    @using (@Ajax.BeginForm("AddProgramNode", "PrivateCategory", new { parentId = Model.aParent }, new AjaxOptions { UpdateTargetId = "" }, new { id = "programForm" }))
    {
        <table>
            <tr><td>@ProgramController.parent</td><td>@Html.LabelForModel(Model.Parent.Name.Matter)</td></tr>
            <tr><td>@ProgramController.code</td><td>@Html.EditorFor(model => model.Code)@Html.ValidationMessageFor(model=>model.Code)</td></tr>
            <tr>
                <td>@ProgramController.name</td>
                <td>
                    @Html.EditorFor(model => model.Name.Matter)
                </td>
             </tr>
            <tr><td>@ProgramController.order</td><td>@Html.EditorFor(model => model.Sorting)</td></tr>
            
            <tr><td><input type="button" value="确认" onclick="submitForm();" /></td><td><input type="reset" value="重置" /></td></tr>
        </table>  
        
    }
</div>

筑巢信息/Zhuchao/LiveAzure/Tools/MyWorkplace_tiangang/Views/PrivateCategory/ProgramNodeEdit.cshtml
@using LiveAzure.Models.General
@using LiveAzure.Resource.Stage;
@using LiveAzure.Resource.Model;
@model GeneralPrivateCategory
<script type="text/javascript" src="@Url.Content("~/Scripts/jquery-1.6.2.js")" ></script>
<script type="text/javascript" src="@Url.Content("~/Scripts/jquery.validate-vsdoc.js")" ></script>
<script src="../../Scripts/jquery-1.6.2.min.js" type="text/javascript"></script>
<script src="../../Scripts/jquery.validate-vsdoc.js" type="text/javascript"></script>
<script type="text/javascript">

    function submitForm() {
        $("#programForm").submit();
    }

    function showProgramNode() {
        document.getElementById("progMain").style.display = "none";
        document.getElementById("progAdd").style.display = "none";
        document.getElementById("progEdit").style.display = "none";
        document.getElementById("progDetail").style.dispaly = "block";
        var id = $("#Gid").val();
        $.ajax({
            type: "GET",
            url: "/PrivateCategory/StandardCategoryItemNode",
            data: { id: id },
            success: function (html) {
                $("#progDetail").html(html);
            }
        });
    }
    
</script>
<div id="Pro" style="margin: 2px;">
    <h2>@ProgramController.editProgramNode</h2>
    @using (@Ajax.BeginForm("SaveStandardCategoryNode", "PrivateCategory", new { gid = Model.Gid }, new AjaxOptions { UpdateTargetId = "" }, new { id = "programForm" }))
    {
        <table>
            <tr>
                <td>@ProgramController.parent
                </td>
                @Html.HiddenFor(model=>model.Gid)
                @if (Model.Parent != null)
                {
                    <td>@Html.LabelForModel(Model.Parent.Name.Matter)
                    </td>
                }
                else {
                    <td>@Html.Label("")
                    </td>
                }
            </tr>
            <tr>
                <td>@ProgramController.code
                </td>
                <td>@Html.EditorFor(model => model.Code)
                </td>
            </tr>
            <tr>
                <td>@ProgramController.name
                </td>
                <td>
                    @Html.EditorFor(model => model.Name.Matter)
                </td>
            </tr>
            <tr>
                <td>@ProgramController.order
                </td>
                <td>@Html.EditorFor(model => model.Sorting)
                </td>
            </tr>
            <tr>
                <td>
                    <input type="button" value="确认" onclick="submitForm();" />
                </td>
                <td>
                    <input type="reset" value="重置" />
                </td>
                <td>
                    <input id="programItem" type="button" value="@LiveAzure.Resource.Stage.ProgramController.itemLink" onclick="showProgramNode()" style="visibility:hidden"/>
                </td>
            </tr>
        </table>  
        
    }
</div>
<script type="text/javascript">
    var showItemButton = $("#Terminal").val();

    if (showItemButton == "true") {
        document.getElementById("programItem").style.visibility = "visible";
    }
</script>