筑巢信息/Zhuchao/LiveAzure/Stage/LiveAzure.Stage/Controllers/WarehouseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using LiveAzure.Models;
using LiveAzure.Models.Member;
using LiveAzure.Models.Warehouse;
using MVC.Controls;
using MVC.Controls.Grid;
using System.Data;
using System.Data.OleDb;
using System.IO;
using System.Transactions;
using System.Text;
using LiveAzure.Models.Shipping;
using LiveAzure.Models.General;
using LiveAzure.Controls.LiveRegionSelector;
using LiveAzure.Models.Order;
using LiveAzure.Models.Product;
using System.Web.Script.Serialization;
using LiveAzure.Models.Purchase;
using LiveAzure.Models.Exchange;
using System.Globalization;
using LiveAzure.BLL;
using System.Windows.Forms;
using System.Drawing;
using LiveAzure.Stage.Helpers;

namespace LiveAzure.Stage.Controllers
{
    public class WarehouseController : BaseController
    {
        public WarehouseBLL whBll;
        public static Guid OrgSelected =Guid.Empty;//当前选中的组织
        public static Guid WarehouseSelected = Guid.Empty;//当前选中的仓库
        #region 库存总账
        /// <summary>
        /// 仓库总账页面
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            // 权限验证
            if (!base.CheckPrivilege())
                return RedirectToAction("ErrorPage", "Home", new { message = "Sorry you have no privilege to visit the Page" });
            return View();
        }
        /// <summary>
        /// 编辑仓库总账的几个字段
        /// </summary>
        /// <param name="ledgerID">要编辑的仓库总账的GUID</param>
        /// <returns></returns>
        public ActionResult LedgerEdit(Guid ledgerID)
        {
            if (!base.CheckPrivilege("EnableEdit"))
                return RedirectToAction("ErrorPage", "Home", new { message = "Sorry you have no privilege to visit the Page" });
            string EnableEdit = "0";
            try
            {
                EnableEdit = CurrentSession.IsAdmin ? "1" : oProgramNodes["EnableEdit"];
            }
            catch (KeyNotFoundException)//捕捉到oProgramNodes没有Key 说明没有授权该节点
            {
                EnableEdit = "0";
            }
            if (EnableEdit == "0")
            {
                return RedirectToAction("ErrorPage", "Home", new { message = "Sorry you have no privilege" });
            }
            WarehouseLedger model = dbEntity.WarehouseLedgers.Find(ledgerID);
            if (model == null|| model.Deleted)
            {
                return Error("记录不存在", Url.Action("Index"));
            }
            return View(model);
        }
        /// <summary>
        /// 将编辑的仓库总账的结果存储到数据库
        /// </summary>
        /// <param name="model">被编辑的仓库总账</param>
        /// <returns></returns>
        public ActionResult LedgerEditDB(WarehouseLedger model)
        {
            if (!base.CheckPrivilege("EnableEdit"))
                return RedirectToAction("ErrorPage", "Home", new { message = "Sorry you have no privilege to visit the Page" });
            WarehouseLedger ledger = dbEntity.WarehouseLedgers.Find(model.Gid);
            if (ledger == null || ledger.Deleted)
            {
                return Error("记录不存在", Url.Action("Index"));
            }
            ledger.MaxQty = model.MaxQty;
            ledger.LockQty = model.LockQty;
            ledger.SafeQty = model.SafeQty;
            dbEntity.SaveChanges();
            return RedirectToAction("Index");
        }
        /// <summary>
        /// 仓库列表
        /// </summary>
        /// <param name="searchModel"></param>
        /// <returns></returns>
        public JsonResult WarehouseLedgerList(SearchModel searchModel, Guid? whID = null, string code ="", string name ="")
        {
            List<WarehouseLedger> warehouseLedgers = (from ledger in dbEntity.WarehouseLedgers.ToList()
                                                join gid in Permission(ModelEnum.UserPrivType.WAREHOUSE) on ledger.WhID equals gid
                                                where (whID == null) ? ledger.WhID==WarehouseSelected : ledger.WhID == whID
                                                && ledger.SkuItem.Code.IndexOf(code, StringComparison.OrdinalIgnoreCase) > -1
                                                && ledger.SkuItem.FullName.Matter.IndexOf(name, StringComparison.OrdinalIgnoreCase) > -1
                                                && !ledger.Deleted
                                                orderby ledger.LastModifyTime
                                                select ledger).ToList();
            int culture = CurrentSession.Culture;
            GridColumnModelList<WarehouseLedger> columns = new GridColumnModelList<WarehouseLedger>();
            columns.Add(p => p.Gid).SetAsPrimaryKey();
            columns.Add(p => p.SkuItem.Barcode);
            columns.Add(p => p.SkuItem.Code);
            columns.Add(p => p.SkuItem.FullName.GetResource(culture)).SetName("SkuID");
            columns.Add(p => p.InQty);
            columns.Add(p => p.OutQty);
            columns.Add(p => p.RealQty);
            columns.Add(p => p.LockQty);
            columns.Add(p => p.CanSaleQty);
            columns.Add(p => p.CanDelivery);
            columns.Add(p => p.TobeDelivery);
            columns.Add(p => p.Arranged);
            columns.Add(p => p.Presale);
            columns.Add(p => p.Ontheway);
            columns.Add(p => p.SafeQty);
            columns.Add(p => p.MaxQty);
            columns.Add(p => p.AverageCost != null ? p.AverageCost.GetResource(CurrentSession.Currency.Value).ToString():"0").SetName("AverageCost");
            GridData gridData = warehouseLedgers.AsQueryable().ToGridData(searchModel,columns);
            return Json(gridData,JsonRequestBehavior.AllowGet);
        }
        
        /// <summary>
        /// 查看总账SKU的详情
        /// </summary>
        /// <param name="ledgerID">要查看的仓库总账的GUID</param>
        /// <returns></returns>
        public ViewResult SKUDetail(Guid ledgerID)
        {
            WarehouseLedger ledger = dbEntity.WarehouseLedgers.Find(ledgerID);
            if (ledger == null || ledger.Deleted)
            {
                return Error("记录不存在", Url.Action("Index"));
            }
            IEnumerable<WarehouseSkuShelf> skuShelves = (from s in dbEntity.WarehouseSkuShelves
                                                        where s.WhID == ledger.WhID
                                                           && s.SkuID == ledger.SkuID
                                                           && !s.Deleted
                                                        orderby s.LastModifyTime
                                                        select s).ToList();
            return View(skuShelves);
        }
        #endregion 库存总账

        #region 货架
        /// <summary>
        /// 货架定义页面
        /// </summary>
        /// <returns>货架View</returns>
        public ActionResult Shelf()
        {
            // 权限验证
            if (!base.CheckPrivilege())
                return RedirectToAction("ErrorPage", "Home", new { message = "Sorry you have no privilege to visit the Page" });
            ViewBag.privEnableEditShelf = GetProgramNode("EnableEditShelf");//允许定义货架
            return View();
        }
        /// <summary>
        /// 返回货架Grid的部分页面
        /// </summary>
        /// <param name="whID">货架对应的仓库的GUID</param>
        /// <returns>包含货架Grid的部分页</returns>
        public ActionResult ShelfGrid(Guid? whID)
        {
            WarehouseInformation model = (from w in dbEntity.WarehouseInformations
                                          where w.Gid == whID
                                             && !w.Deleted
                                          select w).SingleOrDefault();
            if (model == null)
            {
                return Error("记录不存在", Url.Action("Shelf"));
            }
            return PartialView(model);
        }
        /// <summary>
        /// 仓库中的货架
        /// </summary>
        /// <param name="searchModel">SearchModel</param>
        /// <param name="whID">仓库的Gid</param>
        /// <param name="code">用于搜索的Code</param>
        /// <param name="barcode">用于搜索的Barcode</param>
        /// <param name="name">用于搜索的Name</param>
        /// <returns>返回一个仓库里所有货架</returns>
        public JsonResult ShelfList(SearchModel searchModel, Guid? whID = null, string code = "", string barcode = "", string name = "")
        {
            if (whID == null)
                whID = GetCurrentUserPriWhl();
            IEnumerable<WarehouseShelf> WHShelves = (from item in dbEntity.WarehouseShelves.ToList()
                                                     where item.WhID == whID
                                                        && item.Code.IndexOf(code, StringComparison.OrdinalIgnoreCase) > -1
                                                        && item.Barcode.IndexOf(barcode, StringComparison.OrdinalIgnoreCase) > -1
                                                        && item.Name.IndexOf(name, StringComparison.OrdinalIgnoreCase) > -1
                                                        && !item.Deleted
                                                     select item).OrderByDescending(item => item.LastModifyTime);
            GridColumnModelList<WarehouseShelf> columns = new GridColumnModelList<WarehouseShelf>();
            columns.Add(p => p.Gid).SetAsPrimaryKey();
            columns.Add(p => p.Code);
            columns.Add(p => p.Barcode);
            columns.Add(p => p.Name);
            columns.Add(p => p.Reserved);
            columns.Add(p => p.ShelfQuantity);
            columns.Add(p => p.Brief);
            columns.Add(p => p.Remark);
            GridData gridData = WHShelves.AsQueryable().ToGridData(searchModel, columns);

筑巢信息/Zhuchao/LiveAzure/Stage/LiveAzure.Stage/Views/Warehouse/InItemAdd.cshtml
@model LiveAzure.Models.Warehouse.WarehouseInItem
@{
    Layout = null; 
 }
@using CommonResource = LiveAzure.Resource.Common
@using WarehouseInItemResource =  LiveAzure.Resource.Model.Warehouse.WarehouseInItem
@using WCResource = LiveAzure.Resource.Stage.WarehouseController
@ControlManager.SKUSelect()
<h2>WarehouseInItemAdd</h2>
@using (Html.BeginForm("InItemAddDB", "Warehouse", FormMethod.Post, new { id = "InItemAddForm" }))
{
    <table>
        <tr>
            <th>@WarehouseInItemResource.StockIn</th>
            <td>
                @Html.TextBoxFor(model => model.StockIn.Code, new { disabled = "disabled" })
                @Html.HiddenFor(model => model.InID)
            </td>
        </tr>
        <tr>
            <th>@WarehouseInItemResource.SkuItem</th>
            <td>@Html.EditorFor(model => model.SkuID, "SKUSelect", new { ID = "SKU", OrgID = Model.StockIn.Warehouse.aParent })</td>
        </tr>
        <tr>
            <th>@WarehouseInItemResource.Shelf</th>
            <td>@Html.DropDownListFor(model => model.ShelfID, ViewBag.Shelf as IEnumerable<SelectListItem>)</td>
        </tr>
        <tr>
            <th>@WarehouseInItemResource.TrackLot</th>
            <td>@Html.TextBoxFor(model => model.TrackLot, new { id = "txtTrackLot" })</td>
        </tr>
        <tr>
            <th>@WarehouseInItemResource.Quantity</th>
            <td>@Html.TextBoxFor(model => model.Quantity, new { id = "txtQuantity" })</td>
        </tr>
        <tr>
            <th>@WarehouseInItemResource.Guarantee</th>
            <td>@Html.TextBoxFor(model => model.Guarantee, new { id = "txtGuarantee" })</td>
        </tr>
        <tr>
            <th>@WarehouseInItemResource.GenBarcode</th>
            <td>@Html.TextBoxFor(model => model.GenBarcode, new { id = "txtGenBarcode" })</td>
        </tr>
    </table>
    <input type="submit" id="btnAdd" value="@CommonResource.Add" />
    <input type="button" id="btnResetInItem" value="@CommonResource.Reset" />
}

<script type="text/javascript">
    $("#btnResetInItem").click(function () {
        $("#SKUSelect_val").val("");
        $("#SKUSelect_txt").val("");
        $("#txtTrackLot").val("0");
        $("#txtQuantity").val("0");
        $("#txtGuarantee").val("");
        $("#txtGenBarcode").val("");
    });
</script>
<script type="text/javascript">
    var RegxNum = /^[0-9]+(\.[0-9]+)?$/;
    $("#txtQuantity").blur(function () {
        var input = $(this);
        var value = input.val();
        if (!RegxNum.test(value)) {
            alert("@WCResource.WrongNum");
            input.val("@Model.Quantity");
        }
        if (value == "0") {
            alert("@WCResource.NumMustGreaterThanZero");
        }
    });
    $("#txtTrackLot").blur(function () {
        var input = $(this);
        var value = input.val();
        if (!RegxNum.test(value)) {
            alert("@WCResource.WrongNum");
            input.val("@Model.TrackLot");
        }
    });
    $("#txtGenBarcode").blur(function () {
        var input = $(this);
        var value = input.val();
        if (!RegxNum.test(value)) {
            alert("@WCResource.WrongNum");
            input.val("@Model.GenBarcode");
        }
    });
    $("#InItemAddForm").submit(function (e) {
        if ($("#SKU_val").val() == "") {
           alert("@WCResource.SKURequired");
           e.preventDefault(); 
        }
    });
   $("#btnAdd").click(function () {
       if ($("#txtQuantity").val() == 0) {
           alert("数量不能为0");
           return false;
       }
   });
</script>

筑巢信息/Zhuchao/LiveAzure/Stage/LiveAzure.Stage/Views/Warehouse/InItemEdit.cshtml
@{
    Layout = null; 
 }
 @model LiveAzure.Models.Warehouse.WarehouseInItem
@using CommonResource = LiveAzure.Resource.Common
@using WarehouseInItemResource =  LiveAzure.Resource.Model.Warehouse.WarehouseInItem
@using WCResource = LiveAzure.Resource.Stage.WarehouseController
@ControlManager.SKUSelect()

<h2>WarehouseInItemEdit</h2>

@using (Html.BeginForm("InItemEditDB", "Warehouse", FormMethod.Post, new { id = "InItemEditForm" }))
{
    <table>
        <tr>
            <td><b>@WarehouseInItemResource.StockIn</b></td>
            <td>
                @Html.HiddenFor(model => model.Gid, new { id = "hidGid" })    
                @Html.HiddenFor(model => model.InID, new { id = "hidInID" })
                @Html.TextBoxFor(model => model.StockIn.Code, new { disabled = "disabled" })
            </td>
        </tr>
        <tr>
            <td><b>@WarehouseInItemResource.SkuItem</b></td>
            <td>@Html.EditorFor(model => model.SkuID, "SKUSelect", new { ID = "SKU", OrgID = Model.StockIn.Warehouse.aParent })</td>
        </tr>
        <tr>
            <td><b>@WarehouseInItemResource.Shelf</b></td>
            <td>@Html.DropDownListFor(model => model.ShelfID, ViewBag.Shelf as IEnumerable<SelectListItem>)</td>
        </tr>
       <tr>
            <td><b>@WarehouseInItemResource.TrackLot</b></td>
            <td>@Html.TextBoxFor(model => model.TrackLot, new { id = "txtTrackLot" })</td>
        </tr>
        <tr>
            <td><b>@WarehouseInItemResource.Quantity</b></td>
            <td>@Html.TextBoxFor(model => model.Quantity, new { id = "txtQuantity" })</td>
        </tr>
        <tr>
            <td><b>@WarehouseInItemResource.Guarantee</b></td>
            <td>@Html.TextBoxFor(model => model.Guarantee, new { id = "txtGuarantee" })</td>
        </tr>
        <tr>
            <td><b>@WarehouseInItemResource.GenBarcode</b></td>
            <td>@Html.TextBoxFor(model => model.GenBarcode, new { id = "txtGenBarcode" })</td>
        </tr>
    </table>
    <input type="submit" id="btnEdit" value="@CommonResource.Edit" />
    <input type="reset" id="btnResetInItem" value="@CommonResource.Reset" />
}

<script type="text/javascript">
    $("#btnResetInItem").click(function () {
        var itemID = $("#hidGid").val();
        document.location.replace("/Warehouse/InItemEdit?itemID=" + itemID);
    });
</script>
<script type="text/javascript">
    var RegxNum = /^[0-9]+(\.[0-9]+)?$/;
    $("#txtQuantity").blur(function () {
        var input = $(this);
        var value = input.val();
        if (!RegxNum.test(value)) {
            alert("@WCResource.WrongNum");
            input.val("@Model.Quantity");
        }
        if (value == "0") {
            alert("@WCResource.NumMustGreaterThanZero");
        }
    });
    $("#txtTrackLot").blur(function () {
        var input = $(this);
        var value = input.val();
        if (!RegxNum.test(value)) {
            alert("@WCResource.WrongNum");
            input.val("@Model.TrackLot");
        }
    });
    $("#txtGenBarcode").blur(function () {
        var input = $(this);
        var value = input.val();
        if (!RegxNum.test(value)) {
            alert("@WCResource.WrongNum");
            input.val("@Model.GenBarcode");
        }
    });
    $("#InItemEditForm").submit(function (e) {
        if ($("#SKU_val").val() == "") {
            alert("@WCResource.SKURequired");
            e.preventDefault(); 
        }
    });
    $("#btnEdit").click(function () {
        if ($("#txtQuantity").val() == 0) {
            alert("数量不能为0");
            return false;
        }
    });
</script>

筑巢信息/Zhuchao/LiveAzure/Stage/LiveAzure.Stage/Views/Warehouse/LedgerEdit.cshtml
@model LiveAzure.Models.Warehouse.WarehouseLedger
@using CommonResource = LiveAzure.Resource.Common
@using LedgerResource = LiveAzure.Resource.Model.Warehouse.WarehouseLedger
@{
    Layout = null;
}

@using (Html.BeginForm("LedgerEditDB", "Warehouse"))
{
    @Html.HiddenFor(model => model.Gid)
    <table>
        <tr>
            <th>@LedgerResource.LockQty</th>
            <td>@Html.TextBoxFor(model => model.LockQty)</td>
        </tr><tr>
            <th>@LedgerResource.SafeQty</th>
            <td>@Html.TextBoxFor(model => model.SafeQty)</td>
        </tr>
        <tr>
            <th>@LedgerResource.MaxQty</th>
            <td>@Html.TextBoxFor(model => model.MaxQty)</td>
        </tr>
    </table>
    <input type="submit" value="@CommonResource.Edit" />
    <input type="button" id="btnReset" value="@CommonResource.Reset" />
}

筑巢信息/Zhuchao/LiveAzure/Stage/LiveAzure.Stage/Views/Warehouse/MovingAdd.cshtml
@using CommonResource = LiveAzure.Resource.Common
@using WarehouseMovingResource = LiveAzure.Resource.Model.Warehouse.WarehouseMoving
@using WCResource = LiveAzure.Resource.Stage.WarehouseController
@model LiveAzure.Models.Warehouse.WarehouseMoving

<h2>WarehouseMovingAdd</h2>

@{
    List<SelectListItem> ddlWarehouse = ViewBag.WarehouseList as List<SelectListItem>;
    List<SelectListItem> ddlMtype = ViewBag.MtypeList as List<SelectListItem>;
}

@using(Html.BeginForm("MovingAddDB", "Warehouse", FormMethod.Post))
{
    <table>
        <tr>
            <td><b>@WarehouseMovingResource.Code</b></td>
            <td><input type="text" value="@WCResource.AutoGenerate" disabled="disabled" /></td>
        </tr>
        <tr>
            <td><b>@WarehouseMovingResource.OldWarehouse</b></td>
            <td>@Html.DropDownListFor(model => model.OldWhID, ddlWarehouse, new { id = "oldWH" })</td>
        </tr>
        <tr>
            <td><b>@WarehouseMovingResource.NewWarehouse</b></td>
            <td>@Html.DropDownListFor(model => model.NewWhID, ddlWarehouse, new { id = "newWH" })</td>
        </tr>
        <tr>
            <td><b>@WarehouseMovingResource.Mtype</b></td>
            <td>
                @Html.TextBoxFor(model => model.MoveTypeName, new { id = "mType_txt", @readonly = "readonly" })
                @Html.HiddenFor(model => model.Mtype, new { id = "mType_val" })
                @Html.DropDownList("ddlMtype", ddlMtype, new { id = "ddlMtype", style = "display:none" })
            </td>
        </tr>
        <tr>
            <td><b>@WarehouseMovingResource.Total</b></td>
            <td>@Html.TextBoxFor(model => model.Total, new { disabled = "disabled" })</td>
        </tr>
        <tr>
            <td><b>@WarehouseMovingResource.Shipper</b></td>
            <td>@Html.DropDownList("ShipID", new List<SelectListItem>(), new { id = "shipID", disabled = "disabled" })</td>
        </tr>
        <tr>
            <td><b>@WarehouseMovingResource.Reason</b></td>
            <td>@Html.TextAreaFor(model => model.Reason)</td>
        </tr>
        <tr>
            <td><b>@LiveAzure.Resource.Model.ModelBase.Remark</b></td>
            <td>@Html.TextAreaFor(model => model.Remark)</td>
        </tr>
    </table>
    <input type="submit" value="@CommonResource.Add" />
    <input type="reset" value="@CommonResource.Reset" />
    <input type="button" id="btnCancel" value="@CommonResource.Cancel" />
}

<script type="text/javascript">
    function getMovingTypeName(type) {
        var name;
        var list = $("#ddlMtype option");
        $.each(list, function (index, obj) {
            var temp = $(obj).val();
            if (temp == type)
                name = $(obj).text();
        });
        return name;
    }
    function changeMovingType() {
        var type;
        if ($("#oldWH").val() == $("#newWH").val())
            type = "1";
        else type = "0";
            $("#mType_val").val(type);
        var name = getMovingTypeName(type);
        $("#mType_txt").val(name);
    }
    function refreshElement() {
        changeMovingType();
        if ($("#oldWH").val() == $("#newWH").val()) {
            //移货位
            $("#shipID").empty();
            $("#shipID").attr("disabled", "disabled");
        } else {
            //移库
            $("#shipID").attr("disabled", "disabled");

            //刷新下拉列表
            $.post("/Warehouse/GetShippings", { whID: $("#oldWH").val() },
                    function (data) {
                        $("#shipID").empty();
                        $.each(data, function (index, obj) {
                            var item = new Option(obj.Text, obj.Value);
                            $(item).appendTo("#shipID");
                        });
                        $("#shipID").removeAttr("disabled");
                    });
        }
    }
    $("#btnCancel").click(function () {
        $("#childDiv").fadeOut();
        $("#childDiv").empty();
    });
    $("#oldWH").change(function () {
        refreshElement();
    });
    $("#newWH").change(function () {
        refreshElement();
    });
</script>

筑巢信息/Zhuchao/LiveAzure/Stage/LiveAzure.Stage/Views/Warehouse/ShelfAdd.cshtml
@model LiveAzure.Models.Warehouse.WarehouseShelf
@using WarehouseShelfResource = LiveAzure.Resource.Model.Warehouse.WarehouseShelf
@using CommonResource = LiveAzure.Resource.Common
@{
    ViewBag.Title = "WarehouseShelfAdd";
}
<h2>WarehouseShelfAdd</h2>

@using (Html.BeginForm("ShelfAddDB", "Warehouse", FormMethod.Post))
{
    <table>
        <tr>
            <th>@WarehouseShelfResource.Warehouse</th>
            <td>
                @Html.HiddenFor(model => model.WhID)
                @Html.DisplayFor(model => model.Warehouse.FullName, "LocaleMatter", new { ID = "WarehouseName" })
            </td>
        </tr>
        <tr>
            <th>@WarehouseShelfResource.Code</th>
            <td>@Html.TextBoxFor(model => model.Code, new { id = "txtCode" })</td>
        </tr>
        <tr>
            <th>@WarehouseShelfResource.Barcode</th>
            <td>@Html.TextBoxFor(model => model.Barcode, new { id = "txtBarcode" })</td>
        </tr>
        <tr>
            <th>@WarehouseShelfResource.Name</th>
            <td>@Html.TextBoxFor(model => model.Name, new { id = "txtName" })</td>
        </tr>
        <tr>
            <th>@WarehouseShelfResource.Brief</th>
            <td>@Html.TextAreaFor(model => model.Brief, new { id = "txtBrief" })</td>
        </tr>
        <tr>
            <td>@WarehouseShelfResource.Reserved</td>
            <td>@Html.CheckBoxFor(model=>model.Reserved)</td>
        </tr>
        <tr>
            <td>@LiveAzure.Resource.Model.ModelBase.Remark</td>
            <td>@Html.TextAreaFor(model => model.Remark, new { id = "txtRemark" })</td>
        </tr>
    </table>
    <input type="submit" value="@CommonResource.Add" />
    <input type="button" id="btnReset" value="@CommonResource.Reset" />
    <input type="button" id="btnCancel" value="@CommonResource.Cancel" />
}

<script type="text/javascript">
    $("#btnReset").click(function () {
        $("#txtCode").val("");
        $("#txtBarcode").val("");
        $("#txtName").val("");
        $("#txtBrief").val("");
        $("#txtRemark").val("");
    });
    $("btnCancel").click(function () {
        document.location.replace("/Warehouse/Shelf");
    });
</script>

筑巢信息/Zhuchao/LiveAzure/Stage/LiveAzure.Stage/Views/Warehouse/WarehouseStockInAdd.cshtml
@using CategoryType = LiveAzure.Models.ModelEnum.StandardCategoryType
@using CommonResource = LiveAzure.Resource.Common
@using WarehouseStockInResource = LiveAzure.Resource.Model.Warehouse.WarehouseStockIn
@model LiveAzure.Models.Warehouse.WarehouseStockIn
@ControlManager.StandardCategorySelect()
@ControlManager.RefIDSelect()

@using (Html.BeginForm("WarehouseStockInAddDB", "Warehouse"))
{
    @WarehouseStockInResource.Code
    <input type="text" value="自动生成" disabled="disabled" />
    <br /><br />
    @Html.HiddenFor(model => model.WhID, new { id = "hidWHID" })
    @WarehouseStockInResource.InType
    @Html.EditorFor(model => model.InType, "StandardCategorySelect",
        new { Type = CategoryType.STOCKIN, OnClick = "setRefType" })
    <br /><br />
    @WarehouseStockInResource.RefType
    <input id="RefType_txt" disabled="disabled" />
    @Html.HiddenFor(model => model.RefType, new { id = "RefType_val" })
    <br /><br />
    @WarehouseStockInResource.RefID
    @Html.EditorFor(model => model.RefID, "RefIDSelect", new { ID = "RefID", OnError = "refIdError" })

    <br /><br />
    @WarehouseStockInResource.Total
    @Html.TextBoxFor(model => model.Total)
    <br />
    <input type="submit" value="@CommonResource.Add" />
    <input type="button" value="reset" />
    <input type="button" id="btnCancel" value="@CommonResource.Cancel" />
}
<script type="text/javascript">
    $("#btnCancel").click(function () {
        var whID = $("#hidWHID").val();
        document.location.replace("/Warehouse/WarehouseStockIn?whID=" + whID);
    });
    function setRefType(typeID, typeName) {
        $.post("/Warehouse/GetRefTypeJson", { typeID: typeID },
            function (data) {
                if (data.State == true) {
                    //需要单据
                    $("#RefType_val").val(data.Value);
                    $("#RefType_txt").val(data.Name);
                    objRefID.create(parseInt($("#RefType_val").val()));
                } else {
                    //不需要单据
                    $("#RefType_val").val("");
                    $("#RefType_txt").val("");
                    objRefID.destroy();
                }
            });
    }
    function refIdError() {
        alert("Error!");
    }
    $.ajax({
        type: "post",
        url: "/Warehouse/GetRefTypeJson",
        data: { typeID: "@Model.InType" },
        async: false,
        success: function (data) {
            $("#RefType_val").val(data.Value);
            $("#RefType_txt").val(data.Name);
        }
    });
    objRefID.create(1);
</script>