筑巢信息/Zhuchao/LiveAzure/Tools/LiveTest.Weinan/Controllers/PrivilegeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using LiveAzure.Models.Member;
using LiveAzure.Models;
using LiveAzure.Models.General;
using MVC.Controls;
using MVC.Controls.Grid;
using LiveAzure.Models.Warehouse;

namespace LiveTest.Weinan.Controllers
{
    public class PrivilegeController : BaseController
    {
        //
        // GET: /Privilege/

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult PrivilegeDefinition(MemberPrivilege memberPrivilege)
        {
            return View();
        }

        /// <summary>
        /// 新建用户组织授权
        /// </summary>
        /// <returns></returns>
        public string PrivOrgDefinition(MemberPrivilege memPriv, Guid? userID)
        {
            memPriv.User = dbEntity.MemberUsers.Where(o => o.Gid == userID).FirstOrDefault();
            memPriv.Ptype = 2;
            memPriv.Pstatus = 1;
            //if(Request.Form["Pstatus"]==null)
            //{
            //    memPriv.Pstatus = 0;
            //}
            //else 
            //{
            //    memPriv.Pstatus = 1;
            //}
            if (ModelState.IsValid)
            {
                try
                {
                    dbEntity.MemberPrivileges.Add(memPriv);
                    dbEntity.SaveChanges();
                    return memPriv.Gid.ToString();
                }
                catch (System.Data.Entity.Infrastructure.DbUpdateException)//数据库中已存在该条记录
                {
                    var id = dbEntity.MemberPrivileges.Where(o => o.UserID==userID&&o.Ptype==2).Select(o=>o.Gid).FirstOrDefault();
                    return id.ToString();
                }
            }
            else {
                return null;
            }
            
        }

        /// <summary>
        /// 验证输入的用户名是否存在
        /// </summary>
        /// <param name="strUserName"></param>
        /// <returns></returns>
        public string checkUser(string strUserName)
        {
            string strUserID = "";
            byte nResult = 4;
            //如果接收的用户名为空，返回0
            if (String.IsNullOrEmpty(strUserName))
            {
                nResult = 0;
            }
            else
            {
                //创建一个User实例
                MemberUser user = new MemberUser();
                //验证用户名
                try
                {
                    user = dbEntity.MemberUsers.Where(
                        c => c.LoginName == strUserName && c.Deleted == false && c.Ustatus == (byte)ModelEnum.UserStatus.VALID)
                        .FirstOrDefault();
                    strUserID = user.Gid.ToString();
                    Session["userID"] = strUserID;
                    //ViewData["userID"] = userID;
                    //if (user == null)
                    //{
                    //    nResult = 0;
                    //}
                }
                catch (Exception)
                {
                    user = null;
                    nResult = 1;
                }
            }
            return strUserID;
        }

        /// <summary>
        /// 组织授权列表
        /// </summary>
        /// <param name="searchModel"></param>
        /// <returns></returns>
        public ActionResult ListPrivOrganization(SearchModel searchModel)
        {
            IQueryable<MemberOrganization> organs = (from o in dbEntity.MemberOrganizations
                                                     from p in dbEntity.MemberPrivItems
                                                     where (o.Deleted == false && o.Otype == 0 && p.Deleted == false && o.Gid == p.RefID)
                                                     select o).AsQueryable();
            GridColumnModelList<MemberOrganization> columns = new GridColumnModelList<MemberOrganization>();
            columns.Add(p => p.Gid).SetAsPrimaryKey();
            columns.Add(p => p.Code);
            columns.Add(p => p.ShortName.Matter);

            GridData gridData = organs.ToGridData(searchModel, columns);
            return Json(gridData, JsonRequestBehavior.AllowGet);
        }


        /// <summary>
        /// 用户组织授权
        /// </summary>
        /// <returns></returns>
        public ActionResult PrivOrganization(MemberPrivilege memberPrivilege)
        {
            var memberOrganizations = from o in dbEntity.MemberOrganizations.Include("ShortName")
                                      where (o.Deleted == false && o.Otype == 0)
                                      select new
                                      {
                                          Gid = o.Gid,
                                          ShortName = o.ShortName.Matter
                                      };
            ViewBag.memOrg = new SelectList(memberOrganizations, "Gid", "ShortName");
            return View();
        }

        /// <summary>
        /// 保存Ptype=2，即授权组织信息
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public ActionResult PrivOrganization(MemberPrivilege memberPrivilege, int? optitemCount, string prvID)
        {
            Guid id = new Guid(prvID);
            memberPrivilege = (dbEntity.MemberPrivileges.Where(o => o.Gid == id)).Single();
            if (ModelState.IsValid)
            {
                ICollection<MemberPrivItem> memberPrivItems = new List<MemberPrivItem>();
                for (int i = 0; i < optitemCount; i++)
                {
                    MemberPrivItem memberPrivItem = new MemberPrivItem();
                    memberPrivItem.PrivID = memberPrivilege.Gid;
                    memberPrivItem.RefID = new Guid(Request.Form["privOrg" + i]);
                    memberPrivItems.Add(memberPrivItem);
                }
                memberPrivilege.PrivilegeItems = memberPrivItems;

                dbEntity.SaveChanges();
                return RedirectToAction("Index");
            }
            return View();
        }

        /// <summary>
        /// 新建用户渠道授权
        /// </summary>
        /// <returns></returns>
        public string PrivChanDefinition(MemberPrivilege memPriv, Guid? userID)
        {
            memPriv.User = dbEntity.MemberUsers.Where(o => o.Gid == userID).FirstOrDefault();
            memPriv.Ptype = 3;
            memPriv.Pstatus = 1;
            //if(Request.Form["Pstatus"]==null)
            //{
            //    memPriv.Pstatus = 0;
            //}
            //else 
            //{
            //    memPriv.Pstatus = 1;
            //}
            if (ModelState.IsValid)
            {
                try
                {
                    dbEntity.MemberPrivileges.Add(memPriv);
                    dbEntity.SaveChanges();
                    return memPriv.Gid.ToString();
                }
                catch (System.Data.Entity.Infrastructure.DbUpdateException)//数据库中已存在该条记录
                {
                    var id = dbEntity.MemberPrivileges.Where(o => o.UserID == userID && o.Ptype == 3).Select(o => o.Gid).FirstOrDefault();
                    return id.ToString();
                }
            }
            else
            {
                return null;
            }

        }

        /// <summary>
        /// 渠道授权列表
        /// </summary>
        /// <param name="searchModel"></param>
        /// <returns></returns>
        public ActionResult ListPrivChannel(SearchModel searchModel)
        {
            IQueryable<MemberChannel> organs = (from o in dbEntity.MemberChannels.Include("ShortName")
                                                     from p in dbEntity.MemberPrivItems
                                                     where (o.Deleted == false && o.Otype == 1 && p.Deleted == false && o.Gid == p.RefID)
                                                     select o).AsQueryable();
            GridColumnModelList<MemberChannel> columns = new GridColumnModelList<MemberChannel>();
            columns.Add(p => p.Gid).SetAsPrimaryKey();
            columns.Add(p => p.Code);
            columns.Add(p => p.ShortName.Matter);

            GridData gridData = organs.ToGridData(searchModel, columns);
            return Json(gridData, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// 用户渠道授权
        /// </summary>
        /// <returns></returns>
        public ActionResult PrivChannel(MemberPrivilege memberPrivilege)
        {
            //选择Otype=1的渠道组织
            var memberChannels = from o in dbEntity.MemberChannels.Include("ShortName")
                                      where (o.Deleted == false && o.Otype == 1)
                                      select new
                                      {
                                          Gid = o.Gid,
                                          ShortName = o.ShortName.Matter
                                      };
            ViewBag.memOrg = new SelectList(memberChannels, "Gid", "ShortName");
            return View();
        }

        /// <summary>
        /// 保存Ptype=3，即授权渠道信息
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public ActionResult PrivChannel(MemberPrivilege memberPrivilege, int? optitemCount, string prvID)
        {
            Guid id = new Guid(prvID);
            memberPrivilege = (dbEntity.MemberPrivileges.Where(o => o.Gid == id)).Single();
            if (ModelState.IsValid)
            {
                ICollection<MemberPrivItem> memberPrivItems = new List<MemberPrivItem>();
                for (int i = 0; i < optitemCount; i++)
                {
                    MemberPrivItem memberPrivItem = new MemberPrivItem();
                    memberPrivItem.PrivID = memberPrivilege.Gid;

筑巢信息/Zhuchao/LiveAzure/Tools/LiveTest.Weinan/Views/Privilege/DropDown.cshtml
@{
    ViewBag.Title = "DropDown";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>DropDown</h2>
@Html.DropDownList("dropdown", (List<SelectListItem>)ViewBag.matterlist , new { type = "width:150px" })
<input type="button" value="添加" id="add" onclick="getMatter()" />
<script type="text/javascript">
    function getMatter() {
        Dropresult = $("#dropdown").val();
        alert(Dropresult);
        $.post("/Privilege/PrivProgram", { Dropresult: Dropresult }, function (data) {
        });
    }
</script>

筑巢信息/Zhuchao/LiveAzure/Tools/LiveTest.Weinan/Views/Privilege/Editor.cshtml
@{
    ViewBag.Title = "Editor";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Editor</h2>
请输入：<input type="text" id="editor"  />
<input type="button" id="add" value="添加" onclick="edit()" />
<script type="text/javascript">
    function edit() {
        Editresult = $("#editor").val();
        alert(Editresult);
        $.post("/Privilege/PrivProgram", { Editresult: Editresult }, function (data) {
        });
    }
</script>

筑巢信息/Zhuchao/LiveAzure/Tools/LiveTest.Weinan/Views/Privilege/PrivChannel.cshtml
@using MVC.Controls;
@using MVC.Controls.Grid;
@model LiveAzure.Models.Member.MemberPrivilege
           
@{
    ViewBag.Title = "PrivChannel";
}


<h2>PrivChannel</h2>


<div>
       <input type="checkbox" name="Pstatus" value ="启用" checked="checked"/>
       <span>启用</span>
       <input type="button" value = "新建用户授权" onclick="newPriv()"/>
</div>

@using (Html.BeginForm("PrivChannel", "Privilege", FormMethod.Post))
{
     @Html.ValidationSummary(true)

    <div id = "list">
      <input type="hidden" id="optitemCount" name="optitemCount" value="0" />
      <input type="hidden" id="prvID" name="prvID"/>
    @Html.Grid(new GridControl()
        .SetName("grid2")
        .SetPageSize(10)
        .SetIsAutoSize(true)
        .SetHttpVerb(HttpVerbs.Get)
        .SetListUrl("/Privilege/ListPrivChannel")
        .SetHeight("200")
        .SetColumns<LiveAzure.Models.Member.MemberChannel>(cs =>
        {
            cs.Add(x => x.Gid).SetAsPrimaryKey().SetHidden(true);
            cs.Add(x => x.Code).SetCaption(@LiveAzure.Resource.Model.Member.OrganizationBase.Code);
            cs.Add(x => x.ShortName.Matter).SetCaption("渠道" + @LiveAzure.Resource.Model.Member.OrganizationBase.ShortName);
        })
            )
   @* @{string s = @Html.GridDeleteButton(buttonText: "Delete", gridName: "grid", actionUrl: "/Organization/Delete");          
              var aaa =new HtmlString(s);@aaa}*@
    </div>
     <br /><br />
    <div>
       <table border="1">
         <tr>
           <td>
             @LiveAzure.Resource.Model.Member.OrganizationBase.Code
           </td>
           <td>
             @LiveAzure.Resource.Model.Member.OrganizationBase.ShortName
           </td>
         </tr>

         @foreach (var item in ViewBag.memOrg as SelectList)
         { 
            <tr>
              <td>
               <input type="checkbox" name="selectedOrg" id = "selectedOrg" value ="@item.Value" />
              </td>
              <td>
                <input type="hidden" name="shortName" id = "shortName" value ="@item.Text"/>
                @item.Text
              </td>
            </tr>
         }
       </table>
    </div>
 
    <div>
      <input type="button" onclick ="showtable()" value="添加"/>
    </div>

    <div>
      <input type="submit" value="列表保存"/>
    </div>
 

 <script type="text/javascript">
     function showtable() {

         var privOrg = document.getElementById("selectedOrg").value;
         var name = document.getElementById("shortName").value;
         var tb = document.getElementById("grid2");
         var optionItemCount = document.getElementById("optitemCount").value;
         if (privOrg) {
             var row = tb.insertRow(1);
             var cell1 = row.insertCell();
             var cell2 = row.insertCell();
             cell2.innerHTML = privOrg + '<input type="hidden" name="privOrg' + optionItemCount + '" value="' + privOrg + '" />';
             cell1.innerHTML = name + '<input type="hidden" name="shortName' + optionItemCount + '" value="' + shortName + '" />';
             optionItemCount++;
             $("#list").fadeIn("slow");
         }
         document.getElementById("optitemCount").value = optionItemCount;
     }


     function newPriv() {
         var userid = $("#UserID").val();
         var pstatus = $("#Pstatus").attr('checked');
         alert(userid);
         alert(pstatus);
         $.post("/Privilege/PrivChanDefinition", { userID: userid }, function (data) {
             if (data == null) {
             }
             else {
                 $("#prvID").val(data);
             }
         });
     }

     //    function save() {
     //        var optitemCount = $("#optitemCount").val();
     //        var prvID = $("#prvID").val();
     //        $.post("/Privilege/PrivOrganization", { optitemCount: optitemCount, prvID: prvID });
     //    }

</script>
}

筑巢信息/Zhuchao/LiveAzure/Tools/LiveTest.Weinan/Views/Privilege/PrivOrganization.cshtml
@using MVC.Controls;
@using MVC.Controls.Grid;
@model LiveAzure.Models.Member.MemberPrivilege
           
@{
    ViewBag.Title = "PrivOrganization";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<h2>PrivOrganization</h2>


<div>
       <input type="checkbox" name="Pstatus" value ="启用" checked="checked"/>
       <span>启用</span>
       <input type="button" value = "新建用户授权" onclick="newPriv()"/>
</div>

@using (Html.BeginForm("PrivOrganization", "Privilege", FormMethod.Post))
{
     @Html.ValidationSummary(true)

    <div id = "list">
      <input type="hidden" id="optitemCount" name="optitemCount" value="0" />
      <input type="hidden" id="prvID" name="prvID"/>
    @Html.Grid(new GridControl()
        .SetName("grid1")
        .SetPageSize(10)
        .SetIsAutoSize(true)
        .SetHttpVerb(HttpVerbs.Get)
        .SetListUrl("/Privilege/ListPrivOrganization")
        .SetHeight("200")
        .SetColumns<LiveAzure.Models.Member.MemberOrganization>(cs =>
        {
            cs.Add(x => x.Gid).SetAsPrimaryKey().SetHidden(true);
            cs.Add(x => x.Code).SetCaption(@LiveAzure.Resource.Model.Member.OrganizationBase.Code);
            cs.Add(x => x.ShortName.Matter).SetCaption(@LiveAzure.Resource.Model.Member.OrganizationBase.ShortName);
        })
            )
    @{string s = @Html.GridDeleteButton(buttonText: "Delete", gridName: "grid1", actionUrl: "/Organization/Delete");          
              var aaa =new HtmlString(s);@aaa}
    </div>
     <br /><br />
    <div>
       <table border="1">
         <tr>
           <td>
             @LiveAzure.Resource.Model.Member.OrganizationBase.Code
           </td>
           <td>
             @LiveAzure.Resource.Model.Member.OrganizationBase.ShortName
           </td>
         </tr>

         @foreach (var item in ViewBag.memOrg as SelectList)
         { 
            <tr>
              <td>
               <input type="checkbox" name="selectedOrg" id = "selectedOrg" value ="@item.Value" />
              </td>
              <td>
                <input type="hidden" name="shortName" id = "shortName" value ="@item.Text"/>
                @item.Text
              </td>
            </tr>
         }
       </table>
    </div>
 
    <div>
      <input type="button" onclick ="showtable()" value="添加"/>
    </div>

    <div>
      <input type="submit" value="列表保存"/>
    </div>
 

 <script type="text/javascript">
     function showtable() {
        
         var privOrg = document.getElementById("selectedOrg").value;
         var name = document.getElementById("shortName").value;
         var tb = document.getElementById("grid1");
         var optionItemCount = document.getElementById("optitemCount").value;
         if (privOrg) {
             var row = tb.insertRow(1);
             var cell1 = row.insertCell();
             var cell2 = row.insertCell();
             cell2.innerHTML = privOrg + '<input type="hidden" name="privOrg' + optionItemCount + '" value="' + privOrg + '" />';
             cell1.innerHTML = name + '<input type="hidden" name="shortName' + optionItemCount + '" value="' + shortName + '" />';
             optionItemCount++;
             $("#list").fadeIn("slow");
         }
         document.getElementById("optitemCount").value = optionItemCount;
     }

    
     function newPriv() {
         var userid = $("#UserID").val();
         var pstatus = $("#Pstatus").attr('checked');
         alert(userid);
         alert(pstatus);
         $.post("/Privilege/PrivOrgDefinition", { userID: userid }, function (data) {
             if (data == null) {
             }
             else {
                 $("#prvID").val(data);
             }
         });
    }

//    function save() {
//        var optitemCount = $("#optitemCount").val();
//        var prvID = $("#prvID").val();
//        $.post("/Privilege/PrivOrganization", { optitemCount: optitemCount, prvID: prvID });
//    }

</script>
}

筑巢信息/Zhuchao/LiveAzure/Tools/LiveTest.Weinan/Views/Privilege/PrivProduct.cshtml
@using MVC.Controls;
@using MVC.Controls.Grid;

@{
    ViewBag.Title = "PrivSupplier";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<script type="text/javascript" src="@Url.Content("~/Scripts/LiveTree/jquery.ztree-2.6.js")"></script>
<script type="text/javascript" src="@Url.Content("~/Scripts/LiveTree/treeObject.js")"></script>
<h2>PrivProduct</h2>
<script type="text/javascript">
    var nTreeObject = new treeObject();
    nTreeObject.createTree("Producttree", "/Privilege/PrivProductLoad", "/Privilege/PrivProductExpand", "", "", true);
    function showTree() {
        target = document.getElementById("PrivProduct");
        
        if (target.style.display == "none") {
           
        target.style.display="block"}
}
function ablebutton() {
    
    target = document.getElementById("able");
    if (target.disabled == true) {
        
        target.disabled = false;
    }
</script>

<div>
<input type="checkbox"  onclick="ablebutton()"/>
@Html.Label("启用")

</div>
<div>
@Html.Grid(new GridControl()
        .SetName("Productgrid")
        .SetPageSize(10)
        .SetIsAutoSize(true)
        .SetHttpVerb(HttpVerbs.Get)
        .SetListUrl("/Privilege/ProductList")
        .SetHeight("200")
        .SetColumns<LiveAzure.Models.Product.ProductInformation>(cs =>
            {
                cs.Add(x => x.Gid).SetAsPrimaryKey().SetHidden(true);
                cs.Add(x => x.Code).SetCaption("代码");
                cs.Add(x => x.Name.Matter).SetCaption("名称");
                
            })
       )
      
</div>

<input type="button" value="Add" id="able" onclick="showTree()" disabled="disabled"/>
@{string s = @Html.GridDeleteButton(buttonText: "Delete", gridName: "Productgrid", actionUrl: "/Privilege/Delete");          
              var aaa =new HtmlString(s);@aaa}
    <div id="PrivProduct" style="display:none" >
        <ul id ="Producttree" class="tree" style="width:230px; overflow:auto;" >
        </ul>
        <input type="submit" value="submit" />
    </div>

筑巢信息/Zhuchao/LiveAzure/Tools/LiveTest.Weinan/Views/Privilege/PrivProgram.cshtml
@model LiveAzure.Models.Member.MemberPrivilege

@{
    ViewBag.Title = "PrivProgram";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<script type="text/javascript" src="@Url.Content("~/Scripts/LiveTree/jquery-1.4.2.js")"></script>
<script type="text/javascript" src="@Url.Content("~/Scripts/LiveTree/jquery.ztree-2.6.js")"></script>

@*<script type="text/javascript" src="@Url.Content("~/Scripts/LiveTree/treeObject.js")"></script>*@

<h2>PrivProgram</h2>

<div>
<input type="checkbox"  onclick="ablebutton()" id="StatusProg"/>
@Html.Label("启用")
</div>


    <div id="PrivProgram" >
        <ul id ="Programtree" class="tree" style="width:230px; overflow:auto;" >
        </ul>
        <input type="button" value="submit" id="AddProg" onclick="strcat()"/>
    </div>
     <div id="SubPrivProgram">
      <ul id ="SubProgTree" class="tree"  >
        </ul>
        <input type="button" value="DeleteProg" onclick="del()" />
      </div>

<script type="text/javascript">

        var zTree1, zTree2;
        var setting;

        setting = {
            checkable: true,
            editable: true,
            edit_renameBtn: false,
            edit_removeBtn: false,
            async: true, 																	//默认值，不需要用户指定
            asyncUrl: "../Privilege/PrivProgramExpand", 												//用户指定url
            asyncParam: ["id"], 															//用户指定参数
            callback: {
                click: zTreeOnClick
            }
        };
        subsetting = {
            checkable: true,
            editable: true,
            edit_renameBtn: false,
            edit_removeBtn: false,
            async: true, 																	//默认值，不需要用户指定
            asyncUrl: "../Privilege/SubProgramExpand", 												//用户指定url
            asyncParam: ["id"], 															//用户指定参数
            callback: {
                click: zTreeOnClick
            }
        };


        $(document).ready(function () {
            reloadTree();
        });

        var preSelectedNode1;
        var preSelectedNode2;

        function zTreeOnClick(event, treeId, treeNode) {
            
        }


        function reloadTree() {
            $.ajax({
                type: "POST",
                url: "../Privilege/PrivProgramLoad",
                success: function (data) {
                    var testdata = jQuery.parseJSON(data);
                    zTree1 = $("#Programtree").zTree(setting, testdata);
                    $.ajax({
                        type: "POST",
                        url: "../Privilege/SubProgramLoad",
                        success: function (data1) {
                            var testdata1 = jQuery.parseJSON(data1);
                            zTree2 = $("#SubProgTree").zTree(subsetting, testdata1);
                        }
                    });
                }
            });
        }
        function getCount() {
            var tmp = zTree1.getCheckedNodes(true);
            for (var i = 0; i < tmp.length; i++) {
                alert(tmp[i].name + ",open:" + tmp[i].open+",Gid"+tmp[i].id);
            }
        }
        function strcat() {
            var result = "";
            var open = "";
            var tmp = zTree1.getCheckedNodes(true);
            for (var i = 0; i < tmp.length; i++) {
                result += tmp[i].id + ",";
                open += tmp[i].open + ",";

            }
            alert(result);
            alert(open);
            $.post("/Privilege/PrivProgram", { Result: result, Open: open }, function (data) {
            });
        }
        function del() {
            var result = "";
            var open = "";
            var tmp = zTree2.getCheckedNodes(true);
            for (var i = 0; i < tmp.length; i++) {
                result += tmp[i].id + ",";
                open += tmp[i].open + ",";

            }
            alert(result);
            alert(open);
            $.post("/Privilege/DeleteProgrom", { Result: result, Open: open }, function (data) {
            });
        }
        function ablebutton() {
            if ($("#StatusProg").attr('checked')) {
                $("#AddProg").attr("disabled", false);
                $("#DeleteProg").attr("disabled", false);
            }
            else {
                $("#AddProg").attr("disabled", true);
                $("#DeleteProg").attr("disabled", true);
            }
            $.ajax({

                type: "POST",

                url: "/Privilege/DelAllProg",

                data: {},

                datatype: "html",

                success: function (data) {

                    //$("#gridPrivWare").trigger('reloadGrid');

                },

                error: function () {

                    alert("处理失败!");

                }

            });
        }

        $(document).ready(function () {
            if ('@(ViewBag.status)' == 1) {
                $("#StatusProg").attr('checked', true);
                $("#AddProg").attr("disabled", false);
                $("#DeleteProg").attr("disabled", false);
            }
            else {
                $("#StatusProg").attr('checked', false);
                $("#AddProg").attr("disabled", true);
                $("#DeleteProg").attr("disabled", true);
            }
        });
</script>

筑巢信息/Zhuchao/LiveAzure/Tools/LiveTest.Weinan/Views/Privilege/PrivWarehouse.cshtml
@using MVC.Controls;
@using MVC.Controls.Grid;
@model LiveAzure.Models.Member.MemberPrivilege
           
@{
    ViewBag.Title = "PrivWarehouse";
}


<h2>PrivWarehouse</h2>


<div>
       <input type="checkbox" name="Pstatus" value ="启用" checked="checked"/>
       <span>启用</span>
       <input type="button" value = "新建用户授权" onclick="newPriv()"/>
</div>

@using (Html.BeginForm("PrivWarehouse", "Privilege", FormMethod.Post))
{
     @Html.ValidationSummary(true)

    <div id = "list">
      <input type="hidden" id="optitemCount" name="optitemCount" value="0" />
      <input type="hidden" id="prvID" name="prvID"/>
    @Html.Grid(new GridControl()
        .SetName("grid3")
        .SetPageSize(10)
        .SetIsAutoSize(true)
        .SetHttpVerb(HttpVerbs.Get)
        .SetListUrl("/Privilege/ListPrivWarehouse")
        .SetHeight("200")
        .SetColumns<LiveAzure.Models.Warehouse.WarehouseInformation>(cs =>
        {
            cs.Add(x => x.Gid).SetAsPrimaryKey().SetHidden(true);
            cs.Add(x => x.Code).SetCaption("仓库"+@LiveAzure.Resource.Model.Member.OrganizationBase.Code);
            cs.Add(x => x.ShortName.Matter).SetCaption("仓库" + @LiveAzure.Resource.Model.Member.OrganizationBase.ShortName);
        })
            )
   @* @{string s = @Html.GridDeleteButton(buttonText: "Delete", gridName: "grid", actionUrl: "/Organization/Delete");          
              var aaa =new HtmlString(s);@aaa}*@
    </div>
     <br /><br />
    <div>
       <table border="1">
         <tr>
           <td>
             @LiveAzure.Resource.Model.Member.OrganizationBase.Code
           </td>
           <td>
             @LiveAzure.Resource.Model.Member.OrganizationBase.ShortName
           </td>
         </tr>

         @foreach (var item in ViewBag.memOrg as SelectList)
         { 
            <tr>
              <td>
               <input type="checkbox" name="selectedOrg" id = "selectedOrg" value ="@item.Value" />
              </td>
              <td>
                <input type="hidden" name="shortName" id = "shortName" value ="@item.Text"/>
                @item.Text
              </td>
            </tr>
         }
       </table>
    </div>
 
    <div>
      <input type="button" onclick ="showtable()" value="添加"/>
    </div>

    <div>
      <input type="submit" value="列表保存"/>
    </div>
 

 <script type="text/javascript">
     function showtable() {

         var privOrg = document.getElementById("selectedOrg").value;
         var name = document.getElementById("shortName").value;
         var tb = document.getElementById("grid3");
         var optionItemCount = document.getElementById("optitemCount").value;
         if (privOrg) {
             var row = tb.insertRow(1);
             var cell1 = row.insertCell();
             var cell2 = row.insertCell();
             cell2.innerHTML = privOrg + '<input type="hidden" name="privOrg' + optionItemCount + '" value="' + privOrg + '" />';
             cell1.innerHTML = name + '<input type="hidden" name="shortName' + optionItemCount + '" value="' + shortName + '" />';
             optionItemCount++;
             $("#list").fadeIn("slow");
         }
         document.getElementById("optitemCount").value = optionItemCount;
     }


     function newPriv() {
         var userid = $("#UserID").val();
         var pstatus = $("#Pstatus").attr('checked');
         alert(userid);
         alert(pstatus);
         $.post("/Privilege/PrivWareDefinition", { userID: userid }, function (data) {
             if (data == null) {
             }
             else {
                 $("#prvID").val(data);
             }
         });
     }

     //    function save() {
     //        var optitemCount = $("#optitemCount").val();
     //        var prvID = $("#prvID").val();
     //        $.post("/Privilege/PrivOrganization", { optitemCount: optitemCount, prvID: prvID });
     //    }

</script>
}